### ISSUE TITLE
How to get from the <body:Soap> tag?

### ISSUE THREAD

**Issue by macscripter** [opentable/wiremock-body-transformer#10]
Hello,

First of all, congrats for this amazing  software!

My question is, how can I get the value form a tag with ":" ?

For example,
 
`<soap:Envelope>
	<soap:Body>
		<CONVERS2_x002F_1Response xmlns="urn:APTLU0WS.APT.pragmasis.pt">
			<foo>
				<C_USERID>PIPO</C_USERID>
			</foo>
		</CONVERS2_x002F_1Response>
	</soap:Body>
</soap:Envelope>`

My question is, how to get the C_USERID tag?

I see that the $(soap.soap.CONVERS2_x002F_1Response.foo.C_USERID.value) is not working because of the ":" in the <soap:Envelope> and <soap:Body>....

Thank you!

**Comment by macscripter** [comment]
I will respond to my question....

In this case we should the xmlMapper  will ignore the "soap:" ....
So the true object to be reached is:
$(Envelope.Body.CONVERS2_x002F_1Response.foo.C_USERID.value)

That's WITHOUT the "soap:"

Hope this helps anyone that need to perform tests from the real soap messages.

Best regards

**Comment by tranhungt** [comment]
Hi @macscripter, thanks a lot for the discovery! That would be very helpful for others who are also using soap messages.
We can add this to the documentation. Would you like to make a pull request?

**Comment by macscripter** [comment]
Of course I will do it today! And I will create ( if you accept) the new
functions to return dates/timestamp (not only random Integer) because they
are really very useful for virtualization tasks.

Thank again, guys! Nice software!

**Comment by tranhungt** [comment]
Sounds great. :)
