### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by keithdtyler** [opentable/wiremock-body-transformer#12]
Have both wiremock jar and WBT jar in cd. Running with:

    java -cp "wiremock-body-transformer-1.0.8.jar:wiremock-1.57-standalone.jar" \
    com.github.tomakehurst.wiremock.standalone.WireMockServerRunner \
    --extensions com.opentable.extension.BodyTransformer

I get: 

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/opentable/extension/BodyTransformer : Unsupported major.minor version 52.0

OS: OSX El Capitan 10.11.3

**Comment by tranhungt** [comment]
@keithdtyler What Java version are you using? This one requires java 8.

**Comment by tranhungt** [comment]
Closing, as I'm confident this is a java version incompatibility.
Let me know if you're still having issues.
