### ISSUE TITLE
Does not support latest wiremock 2.x version

### ISSUE THREAD

**Issue by vbhagath** [opentable/wiremock-body-transformer#15]
Wiremock library seems to have updated the interface for the Extension. The ResponseTransformers should be implementing the getName() method instead of name().

Error: java.lang.AbstractMethodError: com.opentable.extension.BodyTransformer.getName

Wiremock version : 2.1.10

**Comment by tranhungt** [comment]
Thanks for the heads up. From what I read on Wiremock's main page, version 2.x has a lot of changes from version 1.x, so perhaps this is not the only point of incompatibility. We welcome any pull requests to make this transformer compliant for wiremock 2.x.

**Comment by Aure77** [comment]
I created a pull request https://github.com/opentable/wiremock-body-transformer/pull/16

**Comment by tranhungt** [comment]
Thanks @Aure77 for the pull request.
@vbhagath The new release 2.1.1 now support wiremock 2.x.x.
