### ISSUE TITLE
how to do body transforming for soap request

### ISSUE THREAD

**Issue by srivi1225** [opentable/wiremock-body-transformer#28]
Hi,

I am new to wiremock and wiremock-body-transformer i have a soap request(namespaced) for which i am using wiremock. my response should be dynamic . Response has to be changed based on the request data. i am providing the sample request and response below.

```
<?xml version="1.0"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
               xmlns:xalan="http://xml.apache.org/xslt">
    <soap:Header xmlns:SOAP-SEC="http://schemas.xmlsoap.org/soap/security/2000-12">
        <payloadManifest xmlns="http://www.starstandards.org/webservices/2005/10/transport">
            <manifest contentID="Content0" element="ProcessCreditContract"
                      namespaceURI="http://www.starstandards.org/STAR" version="4.3.3"/>
        </payloadManifest>
    </soap:Header>
    <soap:Body>
        <PutMessage xmlns="http://www.starstandards.org/webservices/2005/10/transport">
            <payload>
                <content id="Content0">
                    <Process xmlns="http://www.starstandards.org/STAR"
                                           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                           xsi:schemaLocation="http://www.starstandards.org/STAR \STAR\Standalone\sample.xsd"
                                           revision="4.3.3" release="8.1-Lite" environment="Production" lang="en-US">
                        <apparea>
                            <Sender>
                                <site>www.abc.com</LogicalId>
                                <Component>validate</Component>
                                <Task>contract</Task>
                            </Sender>
                            <CreationDateTime>2017-07-24T07:51:21-04:00</CreationDateTime>
                            <BODId>ABC220000005170411</BODId>
                        </apparea>
                        <Data>
                            <PersonName>
                                <GivenName>TRACY</GivenName>
                                <MiddleName>RICHARD</MiddleName>
                                <FamilyName>FRITZ</FamilyName>
                                <Suffix>SR</Suffix>
                            </PersonName>
                        </Data>
                    </Process>
                </content>
            </payload>
        </PutMessage>
    </soap:Body>
</soap:Envelope>
```

response should be something like

```
<?xml>
<BODID>ABC220000005170411</BODID>
<provider>abc</provider>
<name>Suffix + GivenName + MiddleName +FamilyName</name>
<status>success</status>
```
i tried with the below xml
```
<root><foo type="string" xmlns="urn:APTLU0WS.APT.pragmasis.pt">Travis</foo></root>
```
and got the response like

```
<xml>
    <name>hello Travis</name>
</xml>

```
it is working fine

if i  have namespaces in the requst xml and not enclose in ```"<root>"``` or if it find ```"<soap>"``` in the request xml  it is not working.

Can you please guide me how to transform without ```"<root>"``` and for the namespaced soap request.

**Comment by okondrashin** [comment]
Hello :)

https://github.com/opentable/wiremock-body-transformer/issues/10

**Comment by srivi1225** [comment]
Hi,

I tried like ```<xml>$(Envelope.Body.PutMessage.payload.content.Process. apparea.Sender. Component.value)</xml>
```
But i am getting ```null``` also i am not adding ```<root>``` tag.

Could you please suggest me what i am doing wrong here.

**Comment by KRoLer** [comment]
Hi @srivi1225,

In your case <root> tag is soap:Envelope, so you should start your path from _Header_ or _Body_ tag.
Hope Body.PutMessage.payload.content.Process.apparea.Sender.Component.value will work fine.

**Comment by srivi1225** [comment]
Hi @KRoLer 

That worked like a charm. thanka a lot.

also i have one query regarding the wiremock stuff

in the aboive question i have the request and response right. instead of getting the response can i send that as input to another soap service??.

Please help me with your inputs.

**Comment by tranhungt** [comment]
Thanks @KRoLer for the help.
@srivi1225 To my understanding, it is not in the intention of the wiremock platform to be able to pass on requests to external services. And it wasn't the intention of this wiremock-body-transformer to do so either. But since the wiremock project is opensource and extensible, I'm sure some type of request passthrough transformer could be written for it.

**Comment by tranhungt** [comment]
@srivi1225 Looks like this ticket has been resolved so I'll close it now.

**Comment by PraveenKumarDN** [comment]
@tranhungt @KRoLer @okondrashin @stevenschlansker @srivi1225  How to parse for the value of below soap request?
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:inc="http://www.service-now.com/incident">
<soapenv:Header/>
<soapenv:Body>
	<ser:request>
                <ser:requestId>654321</ser:requestId>
                <ser:reason>hello world</ser:reason>
    </ser:request>
<sys_id>Kkpravee_Test</sys_id>
</soapenv:Body>
</soapenv:Envelope>

I tried with belows but still getting null in the response:
1. <ser:uniqueResponseId>$(Body.request.requestId.value)</ser:uniqueResponseId>
2. <ser:uniqueResponseId>$(Body.ser:request.ser:requestId.value)</ser:uniqueResponseId>

Please help me where am i doing wrong guyz.
