### ISSUE TITLE
transformed file as request  body to another service

### ISSUE THREAD

**Issue by srivi1225** [opentable/wiremock-body-transformer#31]
hi,

I am using body transformer to transform my response and it is working well.My question is is ther any way to send the transformed response file as input to a service.

1. service abc/verify --should return a response with the transformed data as output
2. service abc/updateVerifyStatus --> should take the response of abc/verify  and run.

is there any way to save the transformed response to a file.

Thanks,
Sri

**Comment by tranhungt** [comment]
Hi @srivi1225 I'm not sure if there's a way to send the response to a different service, or be able to save the response to a file. That would be outside the scope of this transformer, and if such a capability exists it would be from the base WireMock package.
I'd check out the WireMock docs and see if they support any of those things for you. Though, from a quick look, it doesn't seem like they have that functionality built in.
If that's the case, a transformer could be written to add such a feature and extend the capabilities of WireMock for your use case.
http://wiremock.org/docs/getting-started/
http://wiremock.org/docs/extending-wiremock/

**Comment by srivi1225** [comment]
Thank you @tranhungt for your quick reply.
