### ISSUE TITLE
Response is null for soap 

### ISSUE THREAD

**Issue by pradeepkusingh** [opentable/wiremock-body-transformer#37]
I am trying to fetch the value from the request and injecting in my response. but always getting NULL.

**SOAP REQUEST :** 

<soapenv:Envelope xmlns:ser="http://xml.comcast.com/accountmanagement/services" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:typ="http://xml.comcast.com/types" xmlns:typ1="http://xml.comcast.com/accountmanagement/types">
   <soapenv:Header>
      <wsse:Security soapenv:mustUnderstand="1" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
         <wsse:UsernameToken wsu:Id="UsernameToken-08CC34A9F5B164432115099955232841">
            <wsse:Username>actuser</wsse:Username>
            <wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">!hd2Za63a</wsse:Password>
            <wsse:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">nqqNC/VJ3O1h7Xhjo118ZA==</wsse:Nonce>
            <wsu:Created>2017-11-06T19:12:03.281Z</wsu:Created>
         </wsse:UsernameToken>
      </wsse:Security>
      <typ:requestHeader>
         <typ:timestamp>2017-09-13-04:00</typ:timestamp>
         <typ:sourceSystemId>ESP-SPARROW-PO</typ:sourceSystemId>
         
         <typ:sourceSystemUserId>actuser</typ:sourceSystemUserId>
         <typ:sourceServerId>SPARROW_G1_G2</typ:sourceServerId>
         <typ:trackingId>332234542112334441123</typ:trackingId>
      </typ:requestHeader>
   </soapenv:Header>
   <soapenv:Body>
      <ser:getBillingArrangement xmlns="http://xml.comcast.com/common/types" xmlns:ns2="http://xml.comcast.com/accountmanagement/types" xmlns:ns3="http://xml.comcast.com/accountmanagement/service" xmlns:ns4="http://xml.comcast.com/types">
         <ser:getBillingArrangementRequest>
            <ns2:billingArrangementID>
               <ns2:string>8155100092001035</ns2:string>
            </ns2:billingArrangementID>
            <ns2:billingArrangementProfile>
               <ns2:billingArrangementProfile>BILLING_ARRANGEMENT_STATUS</ns2:billingArrangementProfile>
               <ns2:billingArrangementProfile>CONTACT_INFO</ns2:billingArrangementProfile>
               <ns2:billingArrangementProfile>BILLING_ADDRESS_CONTACT</ns2:billingArrangementProfile>
               <ns2:billingArrangementProfile>DELINQUENT_STATUS</ns2:billingArrangementProfile>
            </ns2:billingArrangementProfile>
         </ser:getBillingArrangementRequest>
      </ser:getBillingArrangement>
   </soapenv:Body>
</soapenv:Envelope>

**RESPONSE** : 

Always get NULL for below variable definition. 

<ns2:billingArrangementID>$**(Body.ser:getBillingArrangement.ser:getBillingArrangementRequest.ns2:billingArrangementID.ns2:string)**</ns2:billingArrangementID>

OUTPUT: ns2:billingArrangementID**null**</ns2:billingArrangementID

**Comment by pradeepkusingh** [comment]
OUTPUT: <ns2:billingArrangementID>null</ns2:billingArrangementID>

**Comment by pradeepkusingh** [comment]
I removed all namespaces and it worked.

**Comment by tranhungt** [comment]
Cool. Can we closed this ticket then @pradeepkusingh?

**Comment by pradeepsingh1234** [comment]
yes,  please close it.
